

services:

 
  backend:
    build: ./backend
    container_name: cultivation_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.xxxxxxxxxxxx.supabase.co:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_JWT_SECRET: ${JWT_SECRET}

  ai-service:
    build: ./ai-service
    container_name: cultivation_ai
    ports:
      - "8000:8000"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      AI_MODE: groq

  frontend:
    build: ./frontend-web
    container_name: cultivation_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - ai-service
