

services:

  postgres:
    image: postgres:15-alpine
    container_name: cultivation_db
    environment:
      POSTGRES_DB: cultivation_db1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: cultivation_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cultivation_db1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy

  ai-service:
    build: ./ai-service
    container_name: cultivation_ai
    ports:
      - "8000:8000"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      AI_MODE: groq

  frontend:
    build: ./frontend-web
    container_name: cultivation_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - ai-service

volumes:
  postgres_data: