ALTER TABLE IF EXISTS users
ADD COLUMN IF NOT EXISTS theme_preference VARCHAR(20) NOT NULL DEFAULT 'LIGHT';

ALTER TABLE IF EXISTS users
ADD COLUMN IF NOT EXISTS desktop_mode BOOLEAN NOT NULL DEFAULT FALSE;
