server {
    listen 80;
    server_name localhost 127.0.0.1 _;
master.live;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name agromaster.live www.agromaster.live;

    ssl_certificate /etc/letsencrypt/live/agromaster.live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/agromaster.live/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ai {
        proxy_pass http://ai-service:8000;
        proxy_set_header Host $host;
    }
}